//
//  Workspace.swift
//  gwasuwonManifests
//
//  Created by 김동준 on 5/12/24
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "App",
    projects: [
        "Projects/App"
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
